function [waveform] = cparCreateWaveform(channel, repeat)
% cparCreateWaveformProgram Create a waveform program
%   [waveform] = cparCreateWaveformProgram(channel, repeat) this function
%   creates an empty waveform for pressure outlet no. [channel] that will
%   be repeated [repeat] number of times.
%
% Note:
%   Pressure stimuli is being generated by an interpreter within the cpar
%   device that execute pressure waveform programs consisting of a series
%   of instructions. There are three different instructions:
%
%      STEP : Changes the pressure to a set value
%      INC  : Increases the pressure with a constant rate
%      DEC  : Decreases the pressure with a constant rate
%
%   Each of the instructions has a duration which in the toolbox is
%   specified in seconds. However, internally in the cpar device this is
%   converted into a number of execution cycles. As the interpreter runs
%   with an update rate of 20Hz the time resolution of these instructions
%   are 50ms.
%
%   There is one interpreter for each pressure outlet, and consequently two
%   pressure waveform programs must be set with the cparSetWaveform
%   function before a pressure stimulation can be started with cparStart.
%
% See also, cparWaveform_Step, cparWaveform_Inc, cparWaveform_Dec
waveform = LabBench.Instruments.CPAR.Functions.SetWaveformProgram;
waveform.Channel = channel - 1;
waveform.Repeat = repeat;
